
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;



namespace cfg.item
{

    public sealed class Item :  Bright.Config.BeanBase 
{
    public Item(JsonElement _json) 
    {
        Id = _json.GetProperty("id").GetInt32();
        Name = _json.GetProperty("name").GetString();
        Desc = _json.GetProperty("desc").GetString();
        Price = _json.GetProperty("price").GetInt32();
        UpgradeToItemId = _json.GetProperty("upgrade_to_item_id").GetInt32();
        { if (_json.TryGetProperty("expire_time", out var _j) && _j.ValueKind != JsonValueKind.Null) { ExpireTime = _j.GetInt32(); } else { ExpireTime = null; } }
        BatchUseable = _json.GetProperty("batch_useable").GetBoolean();
    }

    public Item(int id, string name, string desc, int price, int upgrade_to_item_id, int? expire_time, bool batch_useable ) 
    {
        this.Id = id;
        this.Name = name;
        this.Desc = desc;
        this.Price = price;
        this.UpgradeToItemId = upgrade_to_item_id;
        this.ExpireTime = expire_time;
        this.BatchUseable = batch_useable;
    }

    public static Item DeserializeItem(JsonElement _json)
    {
        return new item.Item(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int Price { get; private set; }
    public int UpgradeToItemId { get; private set; }
    public item.Item UpgradeToItemId_Ref { get; private set; }
    /// <summary>
    /// 过期时间
    /// </summary>
    public int? ExpireTime { get; private set; }
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public bool BatchUseable { get; private set; }

    public const int ID = 2107285806;
    public override int GetTypeId() => ID;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.UpgradeToItemId_Ref = (_tables["item.TbItem"] as item.TbItem).GetOrDefault(UpgradeToItemId);
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Price:" + Price + ","
        + "UpgradeToItemId:" + UpgradeToItemId + ","
        + "ExpireTime:" + ExpireTime + ","
        + "BatchUseable:" + BatchUseable + ","
        + "}";
    }
    }
}
